services:
    spring-boot-db:
        image: postgres:alpine
        container_name: egargo.spring-boot-db
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_DB}
          - PGPORT=${DATABASE_PORT}
        command: postgres -c 'max_connections=1000'
        ports:
            - ${DATABASE_PORT}:5432
        expose:
            - ${DATABASE_PORT}
        volumes:
            - egargo-spring-boot-data:/var/lib/postgresql

    keycloak:
        image: quay.io/keycloak/keycloak:25.0.4
        container_name: egargo.spring-boot-keycloak
        environment:
            - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
            - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
        command: start-dev
        ports:
            - 8080:8080

    spring-boot-app:
        image: egargo.spring-boot-app
        container_name: egargo.spring-boot-app
        build:
            context: .
        ports:
            - 28279:28279
        depends_on:
            - spring-boot-db
            - kafka
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
            - SPRING_SECURITY_JWT_SECRET_KEY=${SPRING_SECURITY_JWT_SECRET_KEY}
            - SPRING_SECURITY_JWT_ACCESS_EXP=${SPRING_SECURITY_JWT_ACCESS_EXP}
            - SPRING_SECURITY_JWT_REFRESH_EXP=${SPRING_SECURITY_JWT_REFRESH_EXP}

    zookeeper:
        image: zookeeper
        container_name: egargo.spring-boot-zookeeper
        hostname: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        network_mode: "host"
        ports:
            - 2181:2181
        expose:
            - 2181

    kafka:
        image: bitnami/kafka
        container_name: egargo.spring-boot-kafka
        environment:
          - KAFKA_CFG_NODE_ID=${KAFKA_CFG_NODE_ID}
          - KAFKA_CFG_PROCESS_ROLES=${KAFKA_CFG_PROCESS_ROLES}
          - KAFKA_CFG_LISTENERS=${KAFKA_CFG_LISTENERS}
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
          - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
          - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
          - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
        volumes:
            - egargo-kafka-data:/var/lib/kafka
        network_mode: "host"
        ports:
            - 9092:9092
        expose:
            - 9092
        depends_on:
            - zookeeper

volumes:
    egargo-spring-boot-data:
    egargo-kafka-data:
