spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: spring-docker
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
            maximum-pool-size: 1000
    data:
        web:
            pageable:
                one-indexed-parameters: true
    h2:
        console:
            enable: true
    jpa:
        database: postgresql
        properties:
            hibernate:
                boot:
                    allow_jdbc_metadata_access: false
                jdbc:
                    time_zone: Asia/Manila
        hibernate:
            ddl-auto: update
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: my-group-id
        # consumer:
        #     group-id: my-group-id
        # producer:
        #     retries: 0
        # template:
        #     default-topic: spring-topic
        # advertised:
        #     # listeners: PLAINTEXT://172.19.0.3:9902
        #     listeners: PLAINTEXT://localhost:9902
        #     # auto-offset-reset: earliest
        #     # bootstrap-servers: localhost:9092
        #     # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        #     # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    mail:
        host: ${SPRING_MAIL_HOST}
        port: ${SPRING_MAIL_PORT}
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false

    # security:
    #     oauth2:
    #         client:
    #             provider:
    #                 spring-docker:
    #                     issuer: http://localhost:8080/realms/spring-docker
    #
    #             registration:
    #                 keycloak:
    #                     provider: spring-docker
    #                     authorization-grant-type: authorization_code
    #                     client-id: spring-docker
    #                     client-secret: secret
    #                     scope: openid

server:
    # address: 0.0.0.0
    port: 28279
    # port: 8888
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 2048
security:
    cors:
      allowed-origin: ${SPRING_SECURITY_CORS_ALLOWED_ORIGIN}
      allow-credentials: ${SPRING_SECURITY_CORS_ALLOW_CREDENTIALS}
      max-age: ${SPRING_SECURITY_CORS_MAX_AGE}
    jwt:
        secret-key: ${SPRING_SECURITY_JWT_SECRET_KEY}
        access-expiration-time: ${SPRING_SECURITY_JWT_ACCESS_EXP}
        refresh-expiration-time: ${SPRING_SECURITY_JWT_REFRESH_EXP}
        issuer: ${SPRING_SECURITY_ISSUER}
        subject: ${SPRING_SECURITY_SUBJECT}
